"""добавлены несколько таблиц

Revision ID: 23e276a40dfd
Revises: b83ba762e0bd
Create Date: 2024-10-31 11:43:05.095249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23e276a40dfd'
down_revision: Union[str, None] = 'b83ba762e0bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
