"""создание

Revision ID: 575f8fcdd08c
Revises: 
Create Date: 2024-10-30 22:56:45.247933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '575f8fcdd08c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ban_users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('time_end', sa.TIMESTAMP(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'chat_id')
    )
    op.drop_constraint('commands_command_chat_id_key', 'commands', type_='unique')
    op.alter_column('messages', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('messages', 'message_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.add_column('muted_users', sa.Column('time_end', sa.TIMESTAMP(), nullable=True))
    op.add_column('muted_users', sa.Column('reason', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'muted_users', 'users', ['user_id'], ['id'])
    op.drop_column('muted_users', 'mute_end')
    op.drop_constraint('roles_role_name_chat_id_key', 'roles', type_='unique')
    op.alter_column('user_chats', 'role_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_chats', 'role_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.create_unique_constraint('roles_role_name_chat_id_key', 'roles', ['role_name', 'chat_id'])
    op.add_column('muted_users', sa.Column('mute_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'muted_users', type_='foreignkey')
    op.drop_column('muted_users', 'reason')
    op.drop_column('muted_users', 'time_end')
    op.alter_column('messages', 'message_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('messages', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_unique_constraint('commands_command_chat_id_key', 'commands', ['command', 'chat_id'])
    op.drop_table('ban_users')
    # ### end Alembic commands ###
