"""migration

Revision ID: 957f0009c5a2
Revises: 040c9d9c328c
Create Date: 2024-11-07 16:33:26.888120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957f0009c5a2'
down_revision: Union[str, None] = '040c9d9c328c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'message_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_type', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
